/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWarningsRouteImport } from './routes/_app/warnings'
import { Route as AppVisaoGeralRouteImport } from './routes/_app/visao-geral'
import { Route as AppProjetosRouteImport } from './routes/_app/projetos'
import { Route as AppPlanejamentoRouteImport } from './routes/_app/planejamento'
import { Route as AppPessoasRouteImport } from './routes/_app/pessoas'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppPdiRouteImport } from './routes/_app/pdi'
import { Route as AppMemoriaRouteImport } from './routes/_app/memoria'
import { Route as AppFrequenciaRouteImport } from './routes/_app/frequencia'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppFidRouteImport } from './routes/_app/fid'
import { Route as AppDashboardsRouteImport } from './routes/_app/dashboards'
import { Route as AppComunicadosRouteImport } from './routes/_app/comunicados'
import { Route as AppComercialRouteImport } from './routes/_app/comercial'
import { Route as AppBevNewsRouteImport } from './routes/_app/bev-news'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppAdminPcRouteImport } from './routes/_app/admin-pc'
import { Route as AppEpeasIndexRouteImport } from './routes/_app/epeas.index'
import { Route as AppBevskillsIndexRouteImport } from './routes/_app/bevskills/index'
import { Route as AppBevskillsGerenciarRouteImport } from './routes/_app/bevskills/gerenciar'
import { Route as AppAssessorPersonIdRouteImport } from './routes/_app/assessor.$personId'
import { Route as AppEpeasContratoContratoIdRouteImport } from './routes/_app/epeas.contrato.$contratoId'
import { Route as AppBevskillsCursoCourseIdRouteImport } from './routes/_app/bevskills/curso.$courseId'

const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWarningsRoute = AppWarningsRouteImport.update({
  id: '/warnings',
  path: '/warnings',
  getParentRoute: () => AppRoute,
} as any)
const AppVisaoGeralRoute = AppVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanejamentoRoute = AppPlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasRoute = AppPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPdiRoute = AppPdiRouteImport.update({
  id: '/pdi',
  path: '/pdi',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoriaRoute = AppMemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => AppRoute,
} as any)
const AppFrequenciaRoute = AppFrequenciaRouteImport.update({
  id: '/frequencia',
  path: '/frequencia',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppFidRoute = AppFidRouteImport.update({
  id: '/fid',
  path: '/fid',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsRoute = AppDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AppRoute,
} as any)
const AppComunicadosRoute = AppComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => AppRoute,
} as any)
const AppComercialRoute = AppComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AppRoute,
} as any)
const AppBevNewsRoute = AppBevNewsRouteImport.update({
  id: '/bev-news',
  path: '/bev-news',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPcRoute = AppAdminPcRouteImport.update({
  id: '/admin-pc',
  path: '/admin-pc',
  getParentRoute: () => AppRoute,
} as any)
const AppEpeasIndexRoute = AppEpeasIndexRouteImport.update({
  id: '/epeas/',
  path: '/epeas/',
  getParentRoute: () => AppRoute,
} as any)
const AppBevskillsIndexRoute = AppBevskillsIndexRouteImport.update({
  id: '/bevskills/',
  path: '/bevskills/',
  getParentRoute: () => AppRoute,
} as any)
const AppBevskillsGerenciarRoute = AppBevskillsGerenciarRouteImport.update({
  id: '/bevskills/gerenciar',
  path: '/bevskills/gerenciar',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessorPersonIdRoute = AppAssessorPersonIdRouteImport.update({
  id: '/assessor/$personId',
  path: '/assessor/$personId',
  getParentRoute: () => AppRoute,
} as any)
const AppEpeasContratoContratoIdRoute =
  AppEpeasContratoContratoIdRouteImport.update({
    id: '/epeas/contrato/$contratoId',
    path: '/epeas/contrato/$contratoId',
    getParentRoute: () => AppRoute,
  } as any)
const AppBevskillsCursoCourseIdRoute =
  AppBevskillsCursoCourseIdRouteImport.update({
    id: '/bevskills/curso/$courseId',
    path: '/bevskills/curso/$courseId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/admin-pc': typeof AppAdminPcRoute
  '/agenda': typeof AppAgendaRoute
  '/bev-news': typeof AppBevNewsRoute
  '/comercial': typeof AppComercialRoute
  '/comunicados': typeof AppComunicadosRoute
  '/dashboards': typeof AppDashboardsRoute
  '/fid': typeof AppFidRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/frequencia': typeof AppFrequenciaRoute
  '/memoria': typeof AppMemoriaRoute
  '/pdi': typeof AppPdiRoute
  '/perfil': typeof AppPerfilRoute
  '/pessoas': typeof AppPessoasRoute
  '/planejamento': typeof AppPlanejamentoRoute
  '/projetos': typeof AppProjetosRoute
  '/visao-geral': typeof AppVisaoGeralRoute
  '/warnings': typeof AppWarningsRoute
  '/assessor/$personId': typeof AppAssessorPersonIdRoute
  '/bevskills/gerenciar': typeof AppBevskillsGerenciarRoute
  '/bevskills/': typeof AppBevskillsIndexRoute
  '/epeas/': typeof AppEpeasIndexRoute
  '/bevskills/curso/$courseId': typeof AppBevskillsCursoCourseIdRoute
  '/epeas/contrato/$contratoId': typeof AppEpeasContratoContratoIdRoute
}
export interface FileRoutesByTo {
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/admin-pc': typeof AppAdminPcRoute
  '/agenda': typeof AppAgendaRoute
  '/bev-news': typeof AppBevNewsRoute
  '/comercial': typeof AppComercialRoute
  '/comunicados': typeof AppComunicadosRoute
  '/dashboards': typeof AppDashboardsRoute
  '/fid': typeof AppFidRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/frequencia': typeof AppFrequenciaRoute
  '/memoria': typeof AppMemoriaRoute
  '/pdi': typeof AppPdiRoute
  '/perfil': typeof AppPerfilRoute
  '/pessoas': typeof AppPessoasRoute
  '/planejamento': typeof AppPlanejamentoRoute
  '/projetos': typeof AppProjetosRoute
  '/visao-geral': typeof AppVisaoGeralRoute
  '/warnings': typeof AppWarningsRoute
  '/': typeof AppIndexRoute
  '/assessor/$personId': typeof AppAssessorPersonIdRoute
  '/bevskills/gerenciar': typeof AppBevskillsGerenciarRoute
  '/bevskills': typeof AppBevskillsIndexRoute
  '/epeas': typeof AppEpeasIndexRoute
  '/bevskills/curso/$courseId': typeof AppBevskillsCursoCourseIdRoute
  '/epeas/contrato/$contratoId': typeof AppEpeasContratoContratoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_app/admin-pc': typeof AppAdminPcRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/bev-news': typeof AppBevNewsRoute
  '/_app/comercial': typeof AppComercialRoute
  '/_app/comunicados': typeof AppComunicadosRoute
  '/_app/dashboards': typeof AppDashboardsRoute
  '/_app/fid': typeof AppFidRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/frequencia': typeof AppFrequenciaRoute
  '/_app/memoria': typeof AppMemoriaRoute
  '/_app/pdi': typeof AppPdiRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/pessoas': typeof AppPessoasRoute
  '/_app/planejamento': typeof AppPlanejamentoRoute
  '/_app/projetos': typeof AppProjetosRoute
  '/_app/visao-geral': typeof AppVisaoGeralRoute
  '/_app/warnings': typeof AppWarningsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/assessor/$personId': typeof AppAssessorPersonIdRoute
  '/_app/bevskills/gerenciar': typeof AppBevskillsGerenciarRoute
  '/_app/bevskills/': typeof AppBevskillsIndexRoute
  '/_app/epeas/': typeof AppEpeasIndexRoute
  '/_app/bevskills/curso/$courseId': typeof AppBevskillsCursoCourseIdRoute
  '/_app/epeas/contrato/$contratoId': typeof AppEpeasContratoContratoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/nova-senha'
    | '/recuperar-senha'
    | '/admin-pc'
    | '/agenda'
    | '/bev-news'
    | '/comercial'
    | '/comunicados'
    | '/dashboards'
    | '/fid'
    | '/financeiro'
    | '/frequencia'
    | '/memoria'
    | '/pdi'
    | '/perfil'
    | '/pessoas'
    | '/planejamento'
    | '/projetos'
    | '/visao-geral'
    | '/warnings'
    | '/assessor/$personId'
    | '/bevskills/gerenciar'
    | '/bevskills/'
    | '/epeas/'
    | '/bevskills/curso/$courseId'
    | '/epeas/contrato/$contratoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cadastro'
    | '/login'
    | '/nova-senha'
    | '/recuperar-senha'
    | '/admin-pc'
    | '/agenda'
    | '/bev-news'
    | '/comercial'
    | '/comunicados'
    | '/dashboards'
    | '/fid'
    | '/financeiro'
    | '/frequencia'
    | '/memoria'
    | '/pdi'
    | '/perfil'
    | '/pessoas'
    | '/planejamento'
    | '/projetos'
    | '/visao-geral'
    | '/warnings'
    | '/'
    | '/assessor/$personId'
    | '/bevskills/gerenciar'
    | '/bevskills'
    | '/epeas'
    | '/bevskills/curso/$courseId'
    | '/epeas/contrato/$contratoId'
  id:
    | '__root__'
    | '/_app'
    | '/cadastro'
    | '/login'
    | '/nova-senha'
    | '/recuperar-senha'
    | '/_app/admin-pc'
    | '/_app/agenda'
    | '/_app/bev-news'
    | '/_app/comercial'
    | '/_app/comunicados'
    | '/_app/dashboards'
    | '/_app/fid'
    | '/_app/financeiro'
    | '/_app/frequencia'
    | '/_app/memoria'
    | '/_app/pdi'
    | '/_app/perfil'
    | '/_app/pessoas'
    | '/_app/planejamento'
    | '/_app/projetos'
    | '/_app/visao-geral'
    | '/_app/warnings'
    | '/_app/'
    | '/_app/assessor/$personId'
    | '/_app/bevskills/gerenciar'
    | '/_app/bevskills/'
    | '/_app/epeas/'
    | '/_app/bevskills/curso/$courseId'
    | '/_app/epeas/contrato/$contratoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warnings': {
      id: '/_app/warnings'
      path: '/warnings'
      fullPath: '/warnings'
      preLoaderRoute: typeof AppWarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visao-geral': {
      id: '/_app/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof AppVisaoGeralRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos': {
      id: '/_app/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planejamento': {
      id: '/_app/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AppPlanejamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pessoas': {
      id: '/_app/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof AppPessoasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pdi': {
      id: '/_app/pdi'
      path: '/pdi'
      fullPath: '/pdi'
      preLoaderRoute: typeof AppPdiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memoria': {
      id: '/_app/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof AppMemoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/frequencia': {
      id: '/_app/frequencia'
      path: '/frequencia'
      fullPath: '/frequencia'
      preLoaderRoute: typeof AppFrequenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fid': {
      id: '/_app/fid'
      path: '/fid'
      fullPath: '/fid'
      preLoaderRoute: typeof AppFidRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards': {
      id: '/_app/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AppDashboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comunicados': {
      id: '/_app/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof AppComunicadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comercial': {
      id: '/_app/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AppComercialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bev-news': {
      id: '/_app/bev-news'
      path: '/bev-news'
      fullPath: '/bev-news'
      preLoaderRoute: typeof AppBevNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-pc': {
      id: '/_app/admin-pc'
      path: '/admin-pc'
      fullPath: '/admin-pc'
      preLoaderRoute: typeof AppAdminPcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/epeas/': {
      id: '/_app/epeas/'
      path: '/epeas'
      fullPath: '/epeas/'
      preLoaderRoute: typeof AppEpeasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bevskills/': {
      id: '/_app/bevskills/'
      path: '/bevskills'
      fullPath: '/bevskills/'
      preLoaderRoute: typeof AppBevskillsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bevskills/gerenciar': {
      id: '/_app/bevskills/gerenciar'
      path: '/bevskills/gerenciar'
      fullPath: '/bevskills/gerenciar'
      preLoaderRoute: typeof AppBevskillsGerenciarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessor/$personId': {
      id: '/_app/assessor/$personId'
      path: '/assessor/$personId'
      fullPath: '/assessor/$personId'
      preLoaderRoute: typeof AppAssessorPersonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/epeas/contrato/$contratoId': {
      id: '/_app/epeas/contrato/$contratoId'
      path: '/epeas/contrato/$contratoId'
      fullPath: '/epeas/contrato/$contratoId'
      preLoaderRoute: typeof AppEpeasContratoContratoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bevskills/curso/$courseId': {
      id: '/_app/bevskills/curso/$courseId'
      path: '/bevskills/curso/$courseId'
      fullPath: '/bevskills/curso/$courseId'
      preLoaderRoute: typeof AppBevskillsCursoCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminPcRoute: typeof AppAdminPcRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppBevNewsRoute: typeof AppBevNewsRoute
  AppComercialRoute: typeof AppComercialRoute
  AppComunicadosRoute: typeof AppComunicadosRoute
  AppDashboardsRoute: typeof AppDashboardsRoute
  AppFidRoute: typeof AppFidRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFrequenciaRoute: typeof AppFrequenciaRoute
  AppMemoriaRoute: typeof AppMemoriaRoute
  AppPdiRoute: typeof AppPdiRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPessoasRoute: typeof AppPessoasRoute
  AppPlanejamentoRoute: typeof AppPlanejamentoRoute
  AppProjetosRoute: typeof AppProjetosRoute
  AppVisaoGeralRoute: typeof AppVisaoGeralRoute
  AppWarningsRoute: typeof AppWarningsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssessorPersonIdRoute: typeof AppAssessorPersonIdRoute
  AppBevskillsGerenciarRoute: typeof AppBevskillsGerenciarRoute
  AppBevskillsIndexRoute: typeof AppBevskillsIndexRoute
  AppEpeasIndexRoute: typeof AppEpeasIndexRoute
  AppBevskillsCursoCourseIdRoute: typeof AppBevskillsCursoCourseIdRoute
  AppEpeasContratoContratoIdRoute: typeof AppEpeasContratoContratoIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminPcRoute: AppAdminPcRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppBevNewsRoute: AppBevNewsRoute,
  AppComercialRoute: AppComercialRoute,
  AppComunicadosRoute: AppComunicadosRoute,
  AppDashboardsRoute: AppDashboardsRoute,
  AppFidRoute: AppFidRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFrequenciaRoute: AppFrequenciaRoute,
  AppMemoriaRoute: AppMemoriaRoute,
  AppPdiRoute: AppPdiRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPessoasRoute: AppPessoasRoute,
  AppPlanejamentoRoute: AppPlanejamentoRoute,
  AppProjetosRoute: AppProjetosRoute,
  AppVisaoGeralRoute: AppVisaoGeralRoute,
  AppWarningsRoute: AppWarningsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssessorPersonIdRoute: AppAssessorPersonIdRoute,
  AppBevskillsGerenciarRoute: AppBevskillsGerenciarRoute,
  AppBevskillsIndexRoute: AppBevskillsIndexRoute,
  AppEpeasIndexRoute: AppEpeasIndexRoute,
  AppBevskillsCursoCourseIdRoute: AppBevskillsCursoCourseIdRoute,
  AppEpeasContratoContratoIdRoute: AppEpeasContratoContratoIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
