/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWarningsRouteImport } from './routes/_app/warnings'
import { Route as AppVisaoGeralRouteImport } from './routes/_app/visao-geral'
import { Route as AppReunioesRouteImport } from './routes/_app/reunioes'
import { Route as AppProjetosRouteImport } from './routes/_app/projetos'
import { Route as AppPlanejamentoRouteImport } from './routes/_app/planejamento'
import { Route as AppPessoasRouteImport } from './routes/_app/pessoas'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppPdiRouteImport } from './routes/_app/pdi'
import { Route as AppMemoriaRouteImport } from './routes/_app/memoria'
import { Route as AppLideradosRouteImport } from './routes/_app/liderados'
import { Route as AppGerenteRouteImport } from './routes/_app/gerente'
import { Route as AppFrequenciaRouteImport } from './routes/_app/frequencia'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppFidRouteImport } from './routes/_app/fid'
import { Route as AppDashboardsRouteImport } from './routes/_app/dashboards'
import { Route as AppComunicadosRouteImport } from './routes/_app/comunicados'
import { Route as AppComercialRouteImport } from './routes/_app/comercial'
import { Route as AppBevNewsRouteImport } from './routes/_app/bev-news'
import { Route as AppBenchsRouteImport } from './routes/_app/benchs'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppAdminPcRouteImport } from './routes/_app/admin-pc'
import { Route as AppDiretorIndexRouteImport } from './routes/_app/diretor/index'
import { Route as AppDiretorTodoRouteImport } from './routes/_app/diretor/todo'
import { Route as AppDiretorProblemasRouteImport } from './routes/_app/diretor/problemas'
import { Route as AppDiretorLideradosRouteImport } from './routes/_app/diretor/liderados'
import { Route as AppDiretorDecisoesRouteImport } from './routes/_app/diretor/decisoes'
import { Route as AppDiretorAtasRouteImport } from './routes/_app/diretor/atas'
import { Route as AppAssessorPersonIdRouteImport } from './routes/_app/assessor.$personId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWarningsRoute = AppWarningsRouteImport.update({
  id: '/warnings',
  path: '/warnings',
  getParentRoute: () => AppRoute,
} as any)
const AppVisaoGeralRoute = AppVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AppRoute,
} as any)
const AppReunioesRoute = AppReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanejamentoRoute = AppPlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasRoute = AppPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPdiRoute = AppPdiRouteImport.update({
  id: '/pdi',
  path: '/pdi',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoriaRoute = AppMemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => AppRoute,
} as any)
const AppLideradosRoute = AppLideradosRouteImport.update({
  id: '/liderados',
  path: '/liderados',
  getParentRoute: () => AppRoute,
} as any)
const AppGerenteRoute = AppGerenteRouteImport.update({
  id: '/gerente',
  path: '/gerente',
  getParentRoute: () => AppRoute,
} as any)
const AppFrequenciaRoute = AppFrequenciaRouteImport.update({
  id: '/frequencia',
  path: '/frequencia',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppFidRoute = AppFidRouteImport.update({
  id: '/fid',
  path: '/fid',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsRoute = AppDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AppRoute,
} as any)
const AppComunicadosRoute = AppComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => AppRoute,
} as any)
const AppComercialRoute = AppComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AppRoute,
} as any)
const AppBevNewsRoute = AppBevNewsRouteImport.update({
  id: '/bev-news',
  path: '/bev-news',
  getParentRoute: () => AppRoute,
} as any)
const AppBenchsRoute = AppBenchsRouteImport.update({
  id: '/benchs',
  path: '/benchs',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPcRoute = AppAdminPcRouteImport.update({
  id: '/admin-pc',
  path: '/admin-pc',
  getParentRoute: () => AppRoute,
} as any)
const AppDiretorIndexRoute = AppDiretorIndexRouteImport.update({
  id: '/diretor/',
  path: '/diretor/',
  getParentRoute: () => AppRoute,
} as any)
const AppDiretorTodoRoute = AppDiretorTodoRouteImport.update({
  id: '/diretor/todo',
  path: '/diretor/todo',
  getParentRoute: () => AppRoute,
} as any)
const AppDiretorProblemasRoute = AppDiretorProblemasRouteImport.update({
  id: '/diretor/problemas',
  path: '/diretor/problemas',
  getParentRoute: () => AppRoute,
} as any)
const AppDiretorLideradosRoute = AppDiretorLideradosRouteImport.update({
  id: '/diretor/liderados',
  path: '/diretor/liderados',
  getParentRoute: () => AppRoute,
} as any)
const AppDiretorDecisoesRoute = AppDiretorDecisoesRouteImport.update({
  id: '/diretor/decisoes',
  path: '/diretor/decisoes',
  getParentRoute: () => AppRoute,
} as any)
const AppDiretorAtasRoute = AppDiretorAtasRouteImport.update({
  id: '/diretor/atas',
  path: '/diretor/atas',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessorPersonIdRoute = AppAssessorPersonIdRouteImport.update({
  id: '/assessor/$personId',
  path: '/assessor/$personId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin-pc': typeof AppAdminPcRoute
  '/agenda': typeof AppAgendaRoute
  '/benchs': typeof AppBenchsRoute
  '/bev-news': typeof AppBevNewsRoute
  '/comercial': typeof AppComercialRoute
  '/comunicados': typeof AppComunicadosRoute
  '/dashboards': typeof AppDashboardsRoute
  '/fid': typeof AppFidRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/frequencia': typeof AppFrequenciaRoute
  '/gerente': typeof AppGerenteRoute
  '/liderados': typeof AppLideradosRoute
  '/memoria': typeof AppMemoriaRoute
  '/pdi': typeof AppPdiRoute
  '/perfil': typeof AppPerfilRoute
  '/pessoas': typeof AppPessoasRoute
  '/planejamento': typeof AppPlanejamentoRoute
  '/projetos': typeof AppProjetosRoute
  '/reunioes': typeof AppReunioesRoute
  '/visao-geral': typeof AppVisaoGeralRoute
  '/warnings': typeof AppWarningsRoute
  '/assessor/$personId': typeof AppAssessorPersonIdRoute
  '/diretor/atas': typeof AppDiretorAtasRoute
  '/diretor/decisoes': typeof AppDiretorDecisoesRoute
  '/diretor/liderados': typeof AppDiretorLideradosRoute
  '/diretor/problemas': typeof AppDiretorProblemasRoute
  '/diretor/todo': typeof AppDiretorTodoRoute
  '/diretor/': typeof AppDiretorIndexRoute
}
export interface FileRoutesByTo {
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin-pc': typeof AppAdminPcRoute
  '/agenda': typeof AppAgendaRoute
  '/benchs': typeof AppBenchsRoute
  '/bev-news': typeof AppBevNewsRoute
  '/comercial': typeof AppComercialRoute
  '/comunicados': typeof AppComunicadosRoute
  '/dashboards': typeof AppDashboardsRoute
  '/fid': typeof AppFidRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/frequencia': typeof AppFrequenciaRoute
  '/gerente': typeof AppGerenteRoute
  '/liderados': typeof AppLideradosRoute
  '/memoria': typeof AppMemoriaRoute
  '/pdi': typeof AppPdiRoute
  '/perfil': typeof AppPerfilRoute
  '/pessoas': typeof AppPessoasRoute
  '/planejamento': typeof AppPlanejamentoRoute
  '/projetos': typeof AppProjetosRoute
  '/reunioes': typeof AppReunioesRoute
  '/visao-geral': typeof AppVisaoGeralRoute
  '/warnings': typeof AppWarningsRoute
  '/': typeof AppIndexRoute
  '/assessor/$personId': typeof AppAssessorPersonIdRoute
  '/diretor/atas': typeof AppDiretorAtasRoute
  '/diretor/decisoes': typeof AppDiretorDecisoesRoute
  '/diretor/liderados': typeof AppDiretorLideradosRoute
  '/diretor/problemas': typeof AppDiretorProblemasRoute
  '/diretor/todo': typeof AppDiretorTodoRoute
  '/diretor': typeof AppDiretorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_app/admin-pc': typeof AppAdminPcRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/benchs': typeof AppBenchsRoute
  '/_app/bev-news': typeof AppBevNewsRoute
  '/_app/comercial': typeof AppComercialRoute
  '/_app/comunicados': typeof AppComunicadosRoute
  '/_app/dashboards': typeof AppDashboardsRoute
  '/_app/fid': typeof AppFidRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/frequencia': typeof AppFrequenciaRoute
  '/_app/gerente': typeof AppGerenteRoute
  '/_app/liderados': typeof AppLideradosRoute
  '/_app/memoria': typeof AppMemoriaRoute
  '/_app/pdi': typeof AppPdiRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/pessoas': typeof AppPessoasRoute
  '/_app/planejamento': typeof AppPlanejamentoRoute
  '/_app/projetos': typeof AppProjetosRoute
  '/_app/reunioes': typeof AppReunioesRoute
  '/_app/visao-geral': typeof AppVisaoGeralRoute
  '/_app/warnings': typeof AppWarningsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/assessor/$personId': typeof AppAssessorPersonIdRoute
  '/_app/diretor/atas': typeof AppDiretorAtasRoute
  '/_app/diretor/decisoes': typeof AppDiretorDecisoesRoute
  '/_app/diretor/liderados': typeof AppDiretorLideradosRoute
  '/_app/diretor/problemas': typeof AppDiretorProblemasRoute
  '/_app/diretor/todo': typeof AppDiretorTodoRoute
  '/_app/diretor/': typeof AppDiretorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/admin-pc'
    | '/agenda'
    | '/benchs'
    | '/bev-news'
    | '/comercial'
    | '/comunicados'
    | '/dashboards'
    | '/fid'
    | '/financeiro'
    | '/frequencia'
    | '/gerente'
    | '/liderados'
    | '/memoria'
    | '/pdi'
    | '/perfil'
    | '/pessoas'
    | '/planejamento'
    | '/projetos'
    | '/reunioes'
    | '/visao-geral'
    | '/warnings'
    | '/assessor/$personId'
    | '/diretor/atas'
    | '/diretor/decisoes'
    | '/diretor/liderados'
    | '/diretor/problemas'
    | '/diretor/todo'
    | '/diretor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cadastro'
    | '/login'
    | '/admin-pc'
    | '/agenda'
    | '/benchs'
    | '/bev-news'
    | '/comercial'
    | '/comunicados'
    | '/dashboards'
    | '/fid'
    | '/financeiro'
    | '/frequencia'
    | '/gerente'
    | '/liderados'
    | '/memoria'
    | '/pdi'
    | '/perfil'
    | '/pessoas'
    | '/planejamento'
    | '/projetos'
    | '/reunioes'
    | '/visao-geral'
    | '/warnings'
    | '/'
    | '/assessor/$personId'
    | '/diretor/atas'
    | '/diretor/decisoes'
    | '/diretor/liderados'
    | '/diretor/problemas'
    | '/diretor/todo'
    | '/diretor'
  id:
    | '__root__'
    | '/_app'
    | '/cadastro'
    | '/login'
    | '/_app/admin-pc'
    | '/_app/agenda'
    | '/_app/benchs'
    | '/_app/bev-news'
    | '/_app/comercial'
    | '/_app/comunicados'
    | '/_app/dashboards'
    | '/_app/fid'
    | '/_app/financeiro'
    | '/_app/frequencia'
    | '/_app/gerente'
    | '/_app/liderados'
    | '/_app/memoria'
    | '/_app/pdi'
    | '/_app/perfil'
    | '/_app/pessoas'
    | '/_app/planejamento'
    | '/_app/projetos'
    | '/_app/reunioes'
    | '/_app/visao-geral'
    | '/_app/warnings'
    | '/_app/'
    | '/_app/assessor/$personId'
    | '/_app/diretor/atas'
    | '/_app/diretor/decisoes'
    | '/_app/diretor/liderados'
    | '/_app/diretor/problemas'
    | '/_app/diretor/todo'
    | '/_app/diretor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warnings': {
      id: '/_app/warnings'
      path: '/warnings'
      fullPath: '/warnings'
      preLoaderRoute: typeof AppWarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visao-geral': {
      id: '/_app/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof AppVisaoGeralRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reunioes': {
      id: '/_app/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof AppReunioesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos': {
      id: '/_app/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planejamento': {
      id: '/_app/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AppPlanejamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pessoas': {
      id: '/_app/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof AppPessoasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pdi': {
      id: '/_app/pdi'
      path: '/pdi'
      fullPath: '/pdi'
      preLoaderRoute: typeof AppPdiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memoria': {
      id: '/_app/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof AppMemoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/liderados': {
      id: '/_app/liderados'
      path: '/liderados'
      fullPath: '/liderados'
      preLoaderRoute: typeof AppLideradosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gerente': {
      id: '/_app/gerente'
      path: '/gerente'
      fullPath: '/gerente'
      preLoaderRoute: typeof AppGerenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/frequencia': {
      id: '/_app/frequencia'
      path: '/frequencia'
      fullPath: '/frequencia'
      preLoaderRoute: typeof AppFrequenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fid': {
      id: '/_app/fid'
      path: '/fid'
      fullPath: '/fid'
      preLoaderRoute: typeof AppFidRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards': {
      id: '/_app/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AppDashboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comunicados': {
      id: '/_app/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof AppComunicadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comercial': {
      id: '/_app/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AppComercialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bev-news': {
      id: '/_app/bev-news'
      path: '/bev-news'
      fullPath: '/bev-news'
      preLoaderRoute: typeof AppBevNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/benchs': {
      id: '/_app/benchs'
      path: '/benchs'
      fullPath: '/benchs'
      preLoaderRoute: typeof AppBenchsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-pc': {
      id: '/_app/admin-pc'
      path: '/admin-pc'
      fullPath: '/admin-pc'
      preLoaderRoute: typeof AppAdminPcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diretor/': {
      id: '/_app/diretor/'
      path: '/diretor'
      fullPath: '/diretor/'
      preLoaderRoute: typeof AppDiretorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diretor/todo': {
      id: '/_app/diretor/todo'
      path: '/diretor/todo'
      fullPath: '/diretor/todo'
      preLoaderRoute: typeof AppDiretorTodoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diretor/problemas': {
      id: '/_app/diretor/problemas'
      path: '/diretor/problemas'
      fullPath: '/diretor/problemas'
      preLoaderRoute: typeof AppDiretorProblemasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diretor/liderados': {
      id: '/_app/diretor/liderados'
      path: '/diretor/liderados'
      fullPath: '/diretor/liderados'
      preLoaderRoute: typeof AppDiretorLideradosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diretor/decisoes': {
      id: '/_app/diretor/decisoes'
      path: '/diretor/decisoes'
      fullPath: '/diretor/decisoes'
      preLoaderRoute: typeof AppDiretorDecisoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diretor/atas': {
      id: '/_app/diretor/atas'
      path: '/diretor/atas'
      fullPath: '/diretor/atas'
      preLoaderRoute: typeof AppDiretorAtasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessor/$personId': {
      id: '/_app/assessor/$personId'
      path: '/assessor/$personId'
      fullPath: '/assessor/$personId'
      preLoaderRoute: typeof AppAssessorPersonIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminPcRoute: typeof AppAdminPcRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppBenchsRoute: typeof AppBenchsRoute
  AppBevNewsRoute: typeof AppBevNewsRoute
  AppComercialRoute: typeof AppComercialRoute
  AppComunicadosRoute: typeof AppComunicadosRoute
  AppDashboardsRoute: typeof AppDashboardsRoute
  AppFidRoute: typeof AppFidRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFrequenciaRoute: typeof AppFrequenciaRoute
  AppGerenteRoute: typeof AppGerenteRoute
  AppLideradosRoute: typeof AppLideradosRoute
  AppMemoriaRoute: typeof AppMemoriaRoute
  AppPdiRoute: typeof AppPdiRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPessoasRoute: typeof AppPessoasRoute
  AppPlanejamentoRoute: typeof AppPlanejamentoRoute
  AppProjetosRoute: typeof AppProjetosRoute
  AppReunioesRoute: typeof AppReunioesRoute
  AppVisaoGeralRoute: typeof AppVisaoGeralRoute
  AppWarningsRoute: typeof AppWarningsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssessorPersonIdRoute: typeof AppAssessorPersonIdRoute
  AppDiretorAtasRoute: typeof AppDiretorAtasRoute
  AppDiretorDecisoesRoute: typeof AppDiretorDecisoesRoute
  AppDiretorLideradosRoute: typeof AppDiretorLideradosRoute
  AppDiretorProblemasRoute: typeof AppDiretorProblemasRoute
  AppDiretorTodoRoute: typeof AppDiretorTodoRoute
  AppDiretorIndexRoute: typeof AppDiretorIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminPcRoute: AppAdminPcRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppBenchsRoute: AppBenchsRoute,
  AppBevNewsRoute: AppBevNewsRoute,
  AppComercialRoute: AppComercialRoute,
  AppComunicadosRoute: AppComunicadosRoute,
  AppDashboardsRoute: AppDashboardsRoute,
  AppFidRoute: AppFidRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFrequenciaRoute: AppFrequenciaRoute,
  AppGerenteRoute: AppGerenteRoute,
  AppLideradosRoute: AppLideradosRoute,
  AppMemoriaRoute: AppMemoriaRoute,
  AppPdiRoute: AppPdiRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPessoasRoute: AppPessoasRoute,
  AppPlanejamentoRoute: AppPlanejamentoRoute,
  AppProjetosRoute: AppProjetosRoute,
  AppReunioesRoute: AppReunioesRoute,
  AppVisaoGeralRoute: AppVisaoGeralRoute,
  AppWarningsRoute: AppWarningsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssessorPersonIdRoute: AppAssessorPersonIdRoute,
  AppDiretorAtasRoute: AppDiretorAtasRoute,
  AppDiretorDecisoesRoute: AppDiretorDecisoesRoute,
  AppDiretorLideradosRoute: AppDiretorLideradosRoute,
  AppDiretorProblemasRoute: AppDiretorProblemasRoute,
  AppDiretorTodoRoute: AppDiretorTodoRoute,
  AppDiretorIndexRoute: AppDiretorIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
